import Head from 'next/head'
import styles from '../styles/Home.module.css'
import elements from './elements.json'
import Card from '../components/Card'
import Navbar from '../components/Navbar'
import {MarketContextProvider} from '../context/MarketContext'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MarketContextProvider>
        <Navbar />
        <div className={styles.container}>
          {elements.map((element, key) => <Card
            key={key}
            title={element.title}
            description={element.description}
            image={element.image}
            />)}
       
      </div>
      </MarketContextProvider>
     
    </div>
  )
}
